// /data.js

const products = [
  {
    id: 41,
    name: "Galaxy S25 Ultra with Galaxy AI(1TB Storage)",
    brand: "Samsung",
    category: "Electronics",
    price: 169999.99,
    rating: 4.9,
    image: "images/s25 ultra.jpg",
    description: "Meet the next generation of Galaxy AI. The S25 Ultra is your ultimate companion, powered by the most advanced Galaxy hardware and software.",
  },
  {
    id: 1,
    name: "WH-CH520, Wireless On-ear Bluetooth Headphones",
    brand: "Sony",
    category: "Electronics",
    price: 4499.99,
    rating: 4.5,
    image: "images/MP000000017346208_437Wx649H_2023042511215010.avif",
    description: "Experience immersive sound with these high-quality wireless Bluetooth headphones.",
  },
  {
    id: 2,
    name: "Modern Italian Leather Sofa With Ottoman",
    brand: "ModernLiving",
    category: "Home",
    price: 84999.99,
    rating: 4.8,
    image: "images/image_2_800x_cef44ef9-4ba1-47e4-af57-fecaed194bac_grande.webp",
    description: "A stylish and comfortable leather sofa for your living room.",
  },
  {
    id: 3,
    name: "Classic Men's Watch (FS4835)",
    brand: "Fossil",
    category: "Fashion",
    price: 6999.99,
    rating: 4.6,
    image: "images/FS4835_1.webp",
    description: "A timeless timepiece for the modern man.",
  },
  {
    id: 4,
    name: "Professional EOS 1500D DSLR Camera",
    brand: "Canon",
    category: "Electronics",
    price: 41999.99,
    rating: 4.9,
    image: "images/canon-eos-1500d-dslr-camera-with-18-55-mm-lens-kit-digital-o491362608-p590441094-0-202108121733 (1).jpeg",
    description: "Capture stunning photos and videos with this professional-grade DSLR camera.",
  },
  {
    id: 5,
    name: "Organic Green Tea",
    brand: "Lipton",
    category: "Grocery",
    price: 349.99,
    rating: 4.7,
    image: "images/51kGu7ei4IL._UF1000,1000_QL80_.jpg",
    description: "A refreshing and healthy organic green tea, packed with antioxidants.",
  },
  {
    id: 6,
    name: "ForeverRun NITRO™ Men's Running Shoes",
    brand: "PUMA",
    category: "Fashion",
    price: 13999.99,
    rating: 4.4,
    image: "images/ForeverRun-NITRO™-Men's-Running-Shoes.avif",
    description: "Lightweight and durable running shoes for maximum comfort.",
  },
  {
    id: 7,
    name: "OnePlus 13 5G (12GB RAM, 256GB ROM)",
    brand: "OnePlus",
    category: "Electronics",
    price: 69999.99,
    rating: 4.7,
    image: "images/oneplus.png",
    description: "The latest flagship delivering exceptional performance with a cutting-edge Snapdragon processor.",
  },
  {
    id: 8,
    name: "The Alchemist",
    brand: "Paulo Coelho",
    category: "Books",
    price: 349.99,
    rating: 4.9,
    image: "images/book.webp",
    description: "A bestselling novel that has inspired a devoted following.",
  },
  {
    id: 9,
    name: "Exceed Full Seat and Back Mesh Ergonomic Office Chair",
    brand: "Godrej Interio",
    category: "Home",
    price: 18499.99,
    rating: 4.6,
    image: "images/56101522SD05389_01_1500x1500.avif",
    description: "Improve your posture and comfort during long work hours.",
  },
  {
    id: 10,
    name: "50 inch 125 cm 50CU8000 UHD Smart LED TV",
    brand: "Samsung",
    category: "Electronics",
    price: 52999.99,
    rating: 4.8,
    image: "images/smasung tv.jpg",
    description: "Experience breathtaking clarity and vibrant colors.",
  },
  {
    id: 11,
    name: "Instant Coffee Gold 100 g",
    brand: "Nescafé",
    category: "Grocery",
    price: 699.99,
    rating: 4.9,
    image: "images/61PfDMubrJL.jpg",
    description: "A rich and aromatic blend to start your day right.",
  },
  {
    id: 12,
    name: "0RB3025 Grey Aviator Sunglasses for Men - 62 mm",
    brand: "Ray-Ban",
    category: "Fashion",
    price: 8599.99,
    rating: 4.7,
    image: "images/sungalasses.avif",
    description: "Protect your eyes with style. 100% UV protection.",
  },
  {
    id: 13,
    name: "Black & White Air Force 1 '07 Sneakers",
    brand: "Nike",
    category: "Fashion",
    price: 8699.99,
    rating: 4.5,
    image: "images/AURORA_DV0788-001_PHSLH000-2000.webp",
    description: "Comfortable, durable and timeless—it's number 1 for a reason. The '80s construction pairs with classic colours for style that tracks whether you're on court or on the go.",
  },
  {
    id: 14,
    name: "Galaxy S25 Ultra with Galaxy AI(1TB Storage)",
    brand: "Samsung",
    category: "Electronics",
    price: 159999.99,
    rating: 4.8,
    image: "images/s25 ultra.jpg",
    description: "Meet the future of mobile AI with the S25 Ultra, featuring next-generation performance and camera capabilities.",
  },
  {
    id: 15,
    name: "20000mAh 3i Lithium Polymer Power Bank",
    brand: "Mi",
    category: "Electronics",
    price: 2149.99,
    rating: 4.4,
    image: "images/power bank.jpg",
    description: "Charge your devices on the go with this high-capacity power bank.",
  },
  {
    id: 16,
    name: "Heritage Backpack (25L)",
    brand: "Nike",
    category: "Fashion",
    price: 2799.99,
    rating: 4.6,
    image: "images/backpack.avif",
    description: "A durable and fashionable backpack for daily use or travel.",
  },
  {
    id: 17,
    name: "Blue Solid 6mm Yoga Matt",
    brand: "STRAUSS",
    category: "Home",
    price: 899.99,
    rating: 4.3,
    image: "images/mat.jpg",
    description: "A non-slip, eco-friendly mat for your yoga practice.",
  },
  {
    id: 18,
    name: "Aqua Plus 1.2 Litre Electric Kettle",
    brand: "Havells",
    category: "Home",
    price: 1499.99,
    rating: 4.7,
    image: "images/61SBF33TizS.jpg",
    description: "Boil water quickly and efficiently.",
  },
  {
    id: 19,
    name: "To Kill a Mockingbird",
    brand: "Harper Lee",
    category: "Books",
    price: 399.99,
    rating: 4.9,
    image: "images/81gepf1eMqL._UF1000,1000_QL80_.jpg",
    description: "A powerful story and a classic of modern American literature.",
  },
  {
    id: 20,
    name: "Purple Cotton Polyblend Loose Fit Jackets",
    brand: "The Souled Store",
    category: "Fashion",
    price: 2499.99,
    rating: 4.6,
    image: "images/MP000000024573084_437Wx649H_202411301608575.avif",
    description: "Stay warm and stylish during the cold months.",
  },
  {
    id: 21,
    name: "ROG Spatha X Gaming Mouse",
    brand: "ASUS",
    category: "Electronics",
    price: 13499.99,
    rating: 4.8,
    image: "images/mouse.webp",
    description: "High-precision sensor for ultimate gaming performance.",
  },
  {
    id: 22,
    name: "Pixel 8 Pro - 128 GB - Obsidian",
    brand: "Google",
    category: "Electronics",
    price: 106999.99,
    rating: 4.5,
    image: "images/Google-Pixel-9-Pro-XL_featured-image-packshot-review.png",
    description: "The best of Google's AI in a powerful, pro-level phone.",
  },
  {
    id: 23,
    name: "Extra Virgin Organic Olive Oil 500 ml",
    brand: "Pure Nutrition",
    category: "Grocery",
    price: 999.99,
    rating: 4.7,
    image: "images/61t83QuxHQL.jpg",
    description: "Extra virgin olive oil for healthy and delicious meals.",
  },
  {
    id: 24,
    name: "Acacia Upholstered Queen Size Bed for Bedroom",
    brand: "UrbanLiving",
    category: "Home",
    price: 19999.99,
    rating: 4.4,
    image: "images/bed.jpg",
    description: "A modern wooden bed to elevate your bedroom's aesthetic.",
  },
  {
    id: 25,
    name: "SoundLink Max Bluetooth Speaker ( Black )",
    brand: "Bose",
    category: "Electronics",
    price: 49999.99,
    rating: 4.6,
    image: "images/bose .jpg",
    description: "Compact, portable, and delivers powerful sound.",
  },
  {
    id: 26,
    name: "1984",
    brand: "George Orwell",
    category: "Books",
    price: 199.99,
    rating: 4.8,
    image: "images/1984-original-imahc9p42zyurth5.webp",
    description: "A dystopian masterpiece that remains profoundly relevant.",
  },
  {
    id: 27,
    name: "Premium PU Leather Brown Wallet for Men",
    brand: "UrbanStitch",
    category: "Fashion",
    price: 799.99,
    rating: 4.7,
    image: "images/61oRTX0VuQL._UY1100_.jpg",
    description: "A sleek and durable wallet made from genuine leather.",
  },
  {
    id: 28,
    name: "4.2 Litre Airfryer with Rapid Air Technology",
    brand: "Philips",
    category: "Home",
    price: 8999.99,
    rating: 4.8,
    image: "images/air fryer.jpg",
    description: "Enjoy your favorite fried foods with less oil.",
  },
  {
    id: 29,
    name: "Brew Pro Drip Coffee Machine with Glass Carafe",
    brand: "Borosil",
    category: "Home",
    price: 3199.99,
    rating: 4.6,
    image: "images/french-press.jpg",
    description: "Brew delicious, full-bodied coffee at home.",
  },
  {
    id: 30,
    name: "Galaxy Watch 6 Classic (LTE, 4.7 cm)",
    brand: "Samsung",
    category: "Electronics",
    price: 43999.99,
    rating: 4.7,
    image: "images/smartwatch.jpg",
    description: "Track your fitness, receive notifications, and more.",
  },
  {
    id: 31,
    name: "Pride and Prejudice",
    brand: "Jane Austen",
    category: "Books",
    price: 249.99,
    rating: 4.9,
    image: "images/vintage-book.jpg",
    description: "One of the most popular novels in English literature.",
  },
  {
    id: 32,
    name: "Men's 501'93 Dark Indigo Straight Fit Jeans",
    brand: "Levi's",
    category: "Fashion",
    price: 3599.99,
    rating: 4.5,
    image: "images/jeans.jpg",
    description: "Classic and versatile denim jeans for any occasion.",
  },
  {
    id: 33,
    name: "WF-1000XM5 Noise-Cancelling Earbuds",
    brand: "Sony",
    category: "Electronics",
    price: 24999.99,
    rating: 4.8,
    image: "images/earbuds.jpg",
    description: "Immerse yourself in sound without distractions.",
  },
  {
    id: 34,
    name: "A5 Hardcover Notebook - 12 Pack",
    brand: "Feela",
    category: "Home",
    price: 1199.99,
    rating: 4.6,
    image: "images/notebook.jpg",
    description: "A high-quality notebook for your thoughts and ideas.",
  },
  {
    id: 35,
    name: "Artisanal Pasta",
    brand: "Barilla",
    category: "Grocery",
    price: 329.99,
    rating: 4.7,
    image: "images/pasta.jpg",
    description: "Authentic Italian pasta for a gourmet meal at home.",
  },
  {
    id: 36,
    name: "Men's Silk Scarf Blue-Silver",
    brand: "Gentleman's Choice",
    category: "Fashion",
    price: 1999.99,
    rating: 4.5,
    image: "images/scarf.jpg",
    description: "An elegant and luxurious accessory.",
  },
  {
    id: 37,
    name: "The Lord of the Rings",
    brand: "J.R.R. Tolkien",
    category: "Books",
    price: 999.99,
    rating: 5.0,
    image: "images/fantasy-book.jpg",
    description: "An epic high-fantasy novel by J. R. R. Tolkien.",
  },
  {
    id: 38,
    name: "Galaxy Z Flip5 5G (512GB) Smartphone",
    brand: "Samsung",
    category: "Electronics",
    price: 99999.99,
    rating: 4.4,
    image: "images/z flip.jpg",
    description: "A stunning foldable phone that fits right in your pocket.",
  },
  {
    id: 40,
    name: "Pearl Cashmere Blend Pullover",
    brand: "Everlane",
    category: "Fashion",
    price: 8499.99,
    rating: 4.9,
    image: "images/sweater.jpg",
    description: "Incredibly soft and warm, a true luxury item.",
  },
];